<p style="color: #E43F6F; font-size: 25px;text-align: center"><strong>TP 3: NumPy</strong></p>

<span style="font-size: 18px;margin-bottom:0"><strong>Objectives:</strong></span>
<ul style="list-style: none">
  <li><span style="font-size:11px"> ▶</span> create arrays,</li>
  <li><span style="font-size:11px"> ▶</span> extract the basic properties of arrays,</li>
  <li><span style="font-size:11px"> ▶</span> perform operations with arrays,</li>
  <li><span style="font-size:11px"> ▶</span> implement linear algebra manipulations on matrices (2D arrays),</li>
  <li><span style="font-size:11px"> ▶</span> use functions and subroutines of the NumPy package,</li>
  <li><span style="font-size:11px"> ▶</span> vectorize pieces of code.</li>
</ul>

<span style="color: #E43F6F; font-size: 22px;"><strong>I. Array object</strong></span>

<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>1) Definition</i></span>

The basic object in NumPy is the <tt>ndarray</tt>. It is characterised by a set of properties listed below. For more details, consult the lecture notes <strong>§II.1</strong>.

<span style="color: #1BBAC6; font-size: 16px; margin-left: 4em;"><i>a) The dimension</i></span>

The <span style="color: #AB68B2;"><i>number of dimensions</i></span> of an array is an integer which gives the number of different axes. The number of dimensions of an array is returned using <tt>numpy.ndim</tt>.


<i>Examples:</i> 
<ul style="list-style: none">
  <li><span style="font-size:11px"> ▶</span> a scalar $x$ is a 0D array,</li>
  <li><span style="font-size:11px"> ▶</span> a vector $u_i$ is a 1D array,</li>
  <li><span style="font-size:11px"> ▶</span> a matrix $A_{ij}$ is a 2D array,</li>
  <li><span style="font-size:11px"> ▶</span> a rank-3 tensor $A_{ijk}$ is a 3D array,</li>
  <li><span style="font-size:11px"> ▶</span> etc.</li>
</ul> 

<span style="color: #1BBAC6; font-size: 16px; margin-left: 4em;"><i>b) The axes</i></span>

One <span style="color: #AB68B2;"><i>axis</i></span> of an array is one direction you can move along if you envision a D-dimensional array as a grid (or hypercube). The number of axes is equal to the number of dimensions.

<i>Examples:</i> 
<ul style="list-style: none">
  <li><span style="font-size:11px"> ▶</span> A vector $u_i$ is a 1D array with one axis corresponding to the direction in which the index $i$ varies;
  <li><span style="font-size:11px"> ▶</span> A matrix $A_{ij}$ is a 2D array with two axes: one first "vertical" axis over which the index $i$ varies while the index $j$ is fixed (changing rows), and a second "horizontal" axis over which the index $j$ varies while the index $i$ is fixed (changing columns);
  <li><span style="font-size:11px"> ▶</span> A rank-3 tensor $A_{ijk}$ is a 3D array with three axes,
  <li><span style="font-size:11px"> ▶</span> etc.</li>
</ul> 

<span style="color: #1BBAC6; font-size: 16px; margin-left: 4em;"><i>c) The shape</i></span>

The <span style="color: #AB68B2;"><i>shape</i></span> of an array is the number of elements per axis. The shape of an array is returned using <tt>numpy.shape</tt>.

<i>Examples:</i> 
<ul style="list-style: none">
  <li><span style="font-size:11px"> ▶</span> The shape of a vector is the number of coordinates of the vector;
  <li><span style="font-size:11px"> ▶</span> The shape of a matrix is the number of rows and the number of columns;
  <li><span style="font-size:11px"> ▶</span> etc.</li>
</ul> 

<span style="color: #1BBAC6; font-size: 16px; margin-left: 4em;"><i>d) The size</i></span>

The <span style="color: #AB68B2;"><i>size</i></span> of an array is the total number of elements in the array. The size of an array is returned using <tt>numpy.size</tt>.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px; text-align: center">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code below to understand the manual construction of arrays and the definition of their basic properties. Add appropriate comments when required.</strong></span>
    </td>
  </tr>
</table>

In [2]:
import numpy as np  # NumPy is a package which needs to be loaded before being used (see TP2).
a = np.array([0, 1, 2])
print(a)
print(type(a))
print(np.ndim(a))  # COMMENT REQUIRED
print(np.shape(a))  # COMMENT REQUIRED
print(np.size(a))  # COMMENT REQUIRED
print(a[1])  # COMMENT REQUIRED

[0 1 2]
<class 'numpy.ndarray'>
1
(3,)
3
1


In [ ]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)
print(b.ndim)  # COMMENT REQUIRED
print(b.shape)  # COMMENT REQUIRED
print(b.size)  # COMMENT REQUIRED
print(b[0, 0])  # COMMENT REQUIRED
print(b[0, 1])  # COMMENT REQUIRED

In [ ]:
c = np.array([[[0, 1, 2], [3, 4, 5]], [[7, 8, 9], [10, 11, 12]]])
print(c)
print(c.ndim)  # COMMENT REQUIRED
print(c.shape)  # COMMENT REQUIRED
print(c[0,0,0])  # COMMENT REQUIRED
print(c[0,1,0])  # COMMENT REQUIRED
print(c[0,0,1])  # COMMENT REQUIRED
print(c[1,0,0])  # COMMENT REQUIRED

In [ ]:
a = np.array([0, 1])  # COMMENT REQUIRED
print(a)
b = np.array((0, 1))  # COMMENT REQUIRED
print(b)
c = np.array([(0, 1), (2, 3)])  # COMMENT REQUIRED
print(c)
d = np.array('aa')  # COMMENT REQUIRED
print(d)
print(d.ndim)
e = np.array(42.)  # COMMENT REQUIRED
print(e)
print(e.ndim)

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="sharing.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Extrapolate the way of manually building an array with NumPy and indicate briefly how to extract its basic properties.</strong></span>
    </td>
  </tr>
</table>

<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>2) Types of array elements </i></span>

Arrays elements can be <span style="color: #AB68B2;"><i>all basic types</i></span> in Python, namely, <tt>int</tt>, <tt>float</tt>, <tt>str</tt>, <tt>bool</tt> and <tt>complex</tt>.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the codes below to see examples of arrays with elements of different types. Add comments when required.</strong></span>
    </td>
  </tr>
</table>

In [ ]:
a = np.array([1, 2, 3])
print(a)
print(a.dtype)  # COMMENT REQUIRED
b = np.array([1., 2., 3.])
print(b)
print(b.dtype)  # COMMENT REQUIRED
c = np.array([1. + 1j, 2. + 2j])
print(c)
print(c.dtype)  # COMMENT REQUIRED
d = np.array([True, False])
print(d)
print(d.dtype)  # COMMENT REQUIRED
e = np.array(['hello', 'goodbye', 'hi'])
print(e)
print(e.dtype)  # COMMENT REQUIRED

In [ ]:
a = np.array([1, 2.])  # COMMENT REQUIRED
print(a)
b = np.array([1., 1. + 2.25j])  # COMMENT REQUIRED
print(b)
c = np.array([1, 'a', 1 + 1j])  # COMMENT REQUIRED
print(c)
d = np.array([1, True, False])  # COMMENT REQUIRED
print(d)
e = np.array([2., True, False])  # COMMENT REQUIRED
print(e)
f = np.array([True, 'a', False])  # COMMENT REQUIRED
print(f)

In [ ]:
a = np.array([1, 2, 2.5])
print(a)
b = a.astype(int)  # COMMENT REQUIRED
print(b)
a[2] = 0
print(a)
print(b)  # COMMENT REQUIRED

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="sharing.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Conclude on the types on array elements.</strong></span>
    </td>
  </tr>
</table>

<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>3) Quick construction of regular arrays </i></span>

In the case of regular arrays, there are ways of quickly building them, either using <span style="color: #AB68B2;"><i>lists</i></span> or via <span style="color: #AB68B2;"><i>functions</i></span> of the NumPy package. For more details, consult the lectures notes <strong>§II.1.2</strong>.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the codes below to understand the different ways of quickly building an array and add comments when required.</strong></span>
    </td>
  </tr>
</table>

In [ ]:
a = [[i for i in range(3)] for j in range(4)]  # COMMENT REQUIRED
print(a)
an = np.array(a)
print(an)

a = [[i * j for i in range(3)] for j in range(4)]
print(a)
an = np.array(a)
print(an)

In [ ]:
a = np.arange(15)  # COMMENT REQUIRED
print(a)
b = np.arange(1, 13, 2)  # COMMENT REQUIRED
print(b)
c = np.arange(1, 13, 2, dtype=float)  # COMMENT REQUIRED
print(c)
d = np.arange(0., 1.2, 0.1)  # COMMENT REQUIRED
print(d)

In [ ]:
a = np.linspace(0, 1)  # COMMENT REQUIRED
print(a)
b = np.linspace(0, 1, 10)  # COMMENT REQUIRED
print(b)

In [ ]:
a = np.zeros(10)  # COMMENT REQUIRED
print(a)
b = np.zeros((2, 3))  # COMMENT REQUIRED
print(b)
c = np.ones((3, 2, 3))  # COMMENT REQUIRED
print(c)
d = np.full((3, 4), 2)  # COMMENT REQUIRED
print(d)

In [ ]:
a1 = np.zeros(10, dtype=bool)  # COMMENT REQUIRED
print(a1)
a2 = np.zeros(10, dtype=int)
print(a2)
a3 = np.zeros(10, dtype=float)
print(a3)
a4 = np.zeros(10, dtype=complex)
print(a4)
a5 = np.zeros(10, dtype=str)
print(a5)

In [ ]:
a1 = np.ones(10, dtype=bool)
print(a1)
a2 = np.ones(10, dtype=int)
print(a2)
a3 = np.ones(10, dtype=float)
print(a3)
a4 = np.ones(10, dtype=complex)
print(a4)
a5 = np.ones(10, dtype=str)
print(a5)

In [ ]:
a1 = np.full(10, 2, dtype=bool)
print(a1)
a2 = np.full(10, 2, dtype=int)
print(a2)
a3 = np.full(10, 2, dtype=float)
print(a3)
a4 = np.full(10, 2, dtype=complex)
print(a4)
a5 = np.full(10, 2, dtype=str)
print(a5)

In [ ]:
a = np.identity(3)  # COMMENT REQUIRED
print(a)
b = np.diag([1, 2, 3, 4])  # COMMENT REQUIRED
print(b)

In [ ]:
a = np.empty((3, 4))  # COMMENT REQUIRED
print(a)
b = np.empty((3, 4), dtype=int)  # COMMENT REQUIRED
print(b)
a.fill(3)  # COMMENT REQUIRED
print(a)

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = np.zeros_like(a)  # COMMENT REQUIRED
print(b)
c = np.ones_like(a)  # COMMENT REQUIRED
print(c)
d = np.empty_like(a)  # COMMENT REQUIRED
print(d)
d = np.full_like(a, 3)  # COMMENT REQUIRED
print(d)
a2 = np.array([[1, 2., 3], [4, 5, 6]])
b2 = np.zeros_like(a2)  # COMMENT REQUIRED
print(b2)

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="sharing.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> List the different methods to quickly build regular arrays.</strong></span>
    </td>
  </tr>
</table>

<span style="color: #E43F6F; font-size: 22px;"><strong>II. Basic manipulations of arrays</strong></span>

<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>1) Slicing</i></span>

As with lists, it is possible to specify a subset of the array via <span style="color: #AB68B2;"><i>slicing</i></span>, for partial extraction or partial modification. The syntax is exactly the same as for lists, both for positive and negative indices. For more details, see <strong>§II.2.2</strong> of the lecture notes.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code below to understand how slicing works with arrays. Add appropriate comments when asked.</strong></span>
    </td>
  </tr>
</table>

In [ ]:
a = np.diag([1, 2, 3, 4])
print(a)
print(a[0:2, :]) # lines (lico) takes from 1st to 3rd (3rd excluded), and keep every column, so basically, get rids of the last line
a[0:2, :] = 0 # fill all these with zeros
print(a)
b = a[:, :]  # should create another alias, so change on a affect b
c = np.copy(a)  # obviously a deep copy
print(b)
b[2, 2] = 0
print(b)
print(a)
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1 0 0 0]
 [0 2 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 4]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 4]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 3 0]
 [0 0 0 4]]


<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>2) Shape change</i></span>

It is also possible to <span style="color: #AB68B2;"><i>reshape</i></span> arrays with the command <tt>numpy.reshape</tt>.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code below to understand how shape changing works with arrays. Add appropriate comments when asked.</strong></span>
    </td>
  </tr>
</table>

In [13]:
a = np.ones((3, 4)) # 3D 3 lines x 4 column filled with 1
print(a)
b = np.reshape(a, (2, 6))  # create a copy of a turned into a 2 lines 6 columns ?
print(b)
a.fill(2)
print(a)
print(b)  # it's still a shallow copy, edit of a will edit b aswell
print(b.base is a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]
True


In [12]:
a = np.ones((3, 4)) # 3x4 filled with one
print(np.size(a))
print(a)
print(b.base is b)
print(b)


12
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
False
[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]


<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="sharing.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Draw general conclusions on the shape change of arrays.</strong></span>
    </td>
  </tr>
</table>

<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>3) Concatenation</i></span>

The basic function for <span style="color: #AB68B2;"><i>concatenation</i></span> of arrays is <tt>numpy.concatenate</tt>. For 1D arrays, the behaviour is similar as for the concatenation of lists. However, for n-dimensional arrays, one has to specify the axis along which the concatenation should take place. For more details, consult <strong>§II.2.2</strong> of the lecture notes.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code below to understand how the concatenation of arrays works. Add appropriate comments when asked.</strong></span>
    </td>
  </tr>
</table>

In [16]:
a = np.array([1, 2, 3]) #1D
b = np.array([4, 5, 6]) #1D
c = np.concatenate((a, b))  # merge b at the end of a
d = np.concatenate((a, b, a)) #merge a, then b, then a
print(a)
print(b)
print(c)
print(d)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6 1 2 3]


In [ ]:
a = np.array([[1, 2], [3, 4]]) #2x2 matrixes
b = np.array([[5, 6], [7, 8]])
print(a)
print(b)
c = np.concatenate((a, b), axis=0)  # turns into a 4x2 matrix ? (4 lines)
print(c)
d = np.concatenate((a, b), axis=1)  # turns into a 2x4 matrix
print(d)
e = np.concatenate((a, b), axis=None)  # merge into a 1D ?
print(e)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[1 2 3 4 5 6 7 8]


In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3D array
b = np.array([[[-1, -2, -3], [-4, -5, -6]], [[-7, -8, -9], [-10, -11, -12]]])
print(a)
print(b)
c = np.concatenate((a, b), axis=0)  # merge largest block on top of each other in a weird way
print(c)
d = np.concatenate((a, b), axis=1)  # merge lines on top of each other 
print(d)
e = np.concatenate((a, b), axis=2)  # merge columns together (1 2 3 -1 -2 -3)
print(e)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ -1  -2  -3]
  [ -4  -5  -6]]

 [[ -7  -8  -9]
  [-10 -11 -12]]]
[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]

 [[ -1  -2  -3]
  [ -4  -5  -6]]

 [[ -7  -8  -9]
  [-10 -11 -12]]]
[[[  1   2   3]
  [  4   5   6]
  [ -1  -2  -3]
  [ -4  -5  -6]]

 [[  7   8   9]
  [ 10  11  12]
  [ -7  -8  -9]
  [-10 -11 -12]]]
[[[  1   2   3  -1  -2  -3]
  [  4   5   6  -4  -5  -6]]

 [[  7   8   9  -7  -8  -9]
  [ 10  11  12 -10 -11 -12]]]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7], [8]])
print(a)
print(a.shape) # (2, 3)
print(b)
print(b.shape) # (2, 1)
c = np.concatenate((a, b), axis=1) # so merging columns together, (1, 2, 3, 7)
print(c)
d = np.concatenate((a, b), axis=0)  # so merging lines together, but line arent of the proper size so it should work
print(d)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[7]
 [8]]
(2, 1)
[[1 2 3 7]
 [4 5 6 8]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8])
print(a)
print(b)
print(np.concatenate((a, b), axis=1))  # all input arrays dont match in dimension

[[1 2 3]
 [4 5 6]]
[7 8]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8])
print(a)
print(b)
c = np.concatenate((a, b.reshape((2, 1))), axis=1)
print(b.reshape((2, 1)))  # reshape from (1, 2) to (2, 1) should allow the concatenate
print(c)

[[1 2 3]
 [4 5 6]]
[7 8]
[[7]
 [8]]
[[1 2 3 7]
 [4 5 6 8]]


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.concatenate((a, b))
print(c)
a[0] = 0
print(a)
print(c)  # concatenace create a new object, not a view

[1 2 3 4]
[0 2]
[1 2 3 4]


In [ ]:
a = np.array([True, False])
b = np.array([3. + 2.02j, 4.])
print(a.dtype)
print(b.dtype)
c = np.concatenate((a, b))
print(c)
print(c.dtype)  # concatenate hierarchy bool < int < float < complex, it searchs the common smaller type that can represent everything without loss of information

bool
complex128
[1.+0.j   0.+0.j   3.+2.02j 4.+0.j  ]
complex128


<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="sharing.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Draw general conclusions on how the concatenation of arrays works.</strong></span>
    </td>
  </tr>
</table>

<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>4) Stacking</i></span>

<span style="color: #AB68B2;"><i>Stacking</i></span> of arrays is equivalent to concatenation, but along a new axis. The basic command for stacking is <tt>numpy.stack</tt> but other methods exist for horizontal stacking <tt>numpy.hstack</tt>, vertical stacking <tt>numpy.vstack</tt> or depth stacking <tt>numpy.dstack</tt> (for 2D arrays). For more details, consult <strong>§II.2.2</strong> of the lecture notes.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code below to understand how the stacking of arrays works. Add appropriate comments when asked.</strong></span>
    </td>
  </tr>
</table>

In [24]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.stack((a, b))  # make a (2,2) ?
print(c)
print(c.shape)
d = np.vstack((a, b))  # make a (2,2)?
print(d)
e = np.hstack((a, b))  # make a (1,4) ?
print(e)

[[1 2]
 [3 4]]
(2, 2)
[[1 2]
 [3 4]]
[1 2 3 4]


In [25]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.stack((a, b))  # create a (2, 2, 2) ?
print(c)
print(c.shape)
d = np.dstack((a, b))  # create a (2, 2, 2)
print(d)
e = np.vstack((a, b))  # create a (2, 4, 2) ?
print(e)
f = np.hstack((a, b))  # create a (2, 4)
print(f)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.vstack((a, b))
print(c)
a[0] = 0
print(a)
print(c)  # it's not a view but a brand new one

[[1 2]
 [3 4]]
[0 2]
[[1 2]
 [3 4]]


In [ ]:
a = np.array([1, 2])
b = np.array([True, False])
c = np.vstack((a, b))
print(c)
print(c.dtype)  # same as concatenate, it merge types

[[1 2]
 [1 0]]
int64


<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="sharing.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Draw general conclusions on how the stacking of arrays works.</strong></span>
    </td>
  </tr>
</table>

<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>5) Repetition</i></span>

Sometimes (see later for vectorized calculations), it can be useful to <span style="color: #AB68B2;"><i>repeat</i></span> an array over new dimensions, this is done thanks to the <tt>numpy.tile</tt> command. For more details, consult <strong>§II.2.2</strong> of the lecture notes.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px; text-align: center">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code below to understand how the repetition of arrays along new dimensions works. Add appropriate comments when asked.</strong></span>
    </td>
  </tr>
</table>

In [ ]:
a = np.array([1, 2])
print(np.tile(a, 2))  # repeat the array twice along its current axis
print(np.tile(a, (2, 1)))  # repeat the array twice in one awis, once in the other axis 
print(np.tile(a, (2, 3)))  # repeat the array twice on line and 3 times on columns

[1 2 1 2]
[[1 2]
 [1 2]]
[[1 2 1 2 1 2]
 [1 2 1 2 1 2]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.tile(a, (1, 2)))  # same line wise, but twice in columns
print(np.tile(a, (2, 1)))  # twice in line, same column wise
print(np.tile(a, 2))  # twice in columns (last axis) (numpy completes the command with 1's on the missing axis)
print(np.tile(a, (2, 1, 1)))  # twice in new axis, once line, once column

[[1 2 1 2]
 [3 4 3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 1 2]
 [3 4 3 4]]
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(np.tile(a, 2))  # should copy the last axis, this axis being the 3rd one (1, 1, 2)
print(np.tile(a, (2, 1)))  # careful, it adds 1 to the LEFT, so (1, 2, 1)
print(np.tile(a, (2, 1, 1)))  # (2, 1, 1)

[[[ 1  2  3  1  2  3]
  [ 4  5  6  4  5  6]]

 [[ 7  8  9  7  8  9]
  [10 11 12 10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]
  [ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
a = np.array([1, 2])
b = np.tile(a, 2) # reshape it to (1, 2) so along the same line
print(b)
a[0] = 0
print(b)  # different objects !

[1 2 1 2]
[1 2 1 2]


<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="sharing.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Draw general conclusions on how the repetition of arrays works.</strong></span>
    </td>
  </tr>
</table>

<span style="color: #E43F6F; font-size: 22px;"><strong>III. Basic operations on arrays</strong></span>

<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>1) Element-wise arithmetic operations on numbers</i></span>

The operators <tt>+</tt>, <tt>-</tt>, <tt>*</tt>, <tt>**</tt>, <tt>/</tt>, <tt>//</tt>, <tt>%</tt> have an action "element by element" (element-wise arithmetics) on arrays of the same size containing numbers (<tt>int</tt>, <tt>float</tt>, <tt>complex</tt>).

The comparison operators <tt>==</tt>, <tt><</tt>, <tt>></tt>, <tt><=</tt>, <tt>>=</tt>, <tt>!=</tt> have an action "element by element" (element-wise arithmetics) on arrays of the same size containing numbers and return an array of booleans <tt>bool</tt>.

For more details, consult <strong>§II.3.1</strong> of the lecture notes.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px; text-align: center">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code below to understand how element-wise operations are performed with NumPy arrays containing numbers. Add appropriate comments when required.</strong></span>
    </td>
  </tr>
</table>

In [32]:
a = np.array([20, 30, 40, 50])
b = np.arange(1, 5)
print(a)
print(b)
c = a - b
print(c)
c = a + b
print(c)
c = a * b
print(c)
c = a ** b
print(c)
c = a / b
print(c)
c = a // b
print(c)
c = a % b
print(c)

[20 30 40 50]
[1 2 3 4]
[19 28 37 46]
[21 32 43 54]
[ 20  60 120 200]
[     20     900   64000 6250000]
[20.         15.         13.33333333 12.5       ]
[20 15 13 12]
[0 0 1 2]


In [33]:
a = np.array([1., 2., 3.])
a += 1.
print(a)

[2. 3. 4.]


In [ ]:
a = np.array([1., 2., 3.])
a += 1j
print(a)  # doesnt work, tyep has to be the same for this way of doing so, but you can do a = a + 1j bcs it creates a new table

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'

In [35]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])
c = a < b
print(c)
c = a > b
print(c)
c = a == b
print(c)
c = a != b
print(c)
c = a <= b
print(c)
c = a >= b
print(c)

[ True False False]
[False False  True]
[False  True False]
[ True False  True]
[ True  True False]
[False  True  True]


<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>2) Element-wise arithmetic operations on strings</i></span>

The operator <tt>+</tt> has an action "element by element" (element-wise arithmetics) on arrays of the same size containing strings <tt>str</tt>. However, the operator <tt>*</tt> between <tt>str</tt> and <tt>int</tt> cannot be performed element-wise. For more details, consult <strong>§II.3.1</strong> of the lecture notes.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px; text-align: center">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code below to understand how element-wise operations are performed with NumPy arrays containing strings.</strong></span>
    </td>
  </tr>
</table>

In [36]:
a = np.array(['a', 'b', 'c'])
b = np.array(['z', 'y', 'x'])
c = a + b
print(c)

['az' 'by' 'cx']


In [37]:
a = np.array(['a', 'b', 'c'])
b = np.array([1, 2, 3])
c = a * b
print(c)

TypeError: The 'out' kwarg is necessary. Use numpy.strings.multiply without it.

<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>3) Element-wise arithmetic operations on booleans</i></span>

The operators <tt>not</tt>, <tt>and</tt>, <tt>or</tt> cannot be performed element-wise for arrays containing booleans <tt>bool</tt>. However, they have equivalent (respectively <tt>~</tt>, <tt>&</tt>, <tt>|</tt>) which perform element-wise operations on boolean arrays. For more details, consult <strong>§II.3.1</strong> of the lecture notes.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px; text-align: center">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code below to understand how element-wise operations are performed with NumPy arrays containing booleans.</strong></span>
    </td>
  </tr>
</table>

In [38]:
a = np.array([True, False, True])
c = not a
print(c)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [39]:
a = np.array([True, False, True])
b = np.array([False, False, True])
c = a and b
print(c)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [40]:
a = np.array([True, False, True])
b = np.array([False, False, True])
c = a or b
print(c)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [41]:
a = np.array([True, False, True])
c = ~a
print(c)

[False  True False]


In [42]:
a = np.array([True, False, True])
b = np.array([False, False, True])
c = a & b
print(c)

[False False  True]


In [43]:
a = np.array([True, False, True])
b = np.array([False, False, True])
c = a | b
print(c)

[ True False  True]


<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>4) Reduction operations</i></span>

Some basic functions, called <span style="color: #AB68B2;"><i>reduction operations</i></span>, because they tend to decrease the dimension of the array, are already implemented in NumPy. Most of the time they replace <tt>for</tt> loops.

More involved functions (but also more efficient versions of the functions present in NumPy) are available in the sub-module <tt>scipy.stats</tt> (see TP5).

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code which illustrates the different reduction operations. Add appropriate comments when required.</strong></span>
    </td>
  </tr>
</table>

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.sum(a))  # sum every element of a ?
print(np.sum(a, axis=0))  # sum every element of a along axis 0, so 4, 6 ?
print(np.sum(a, axis=1))  # along axis 1, so 3, 7 ?
print(np.min(a))  # smallest element of a
print(np.max(a))  # highest element of a
print(np.min(a, axis=0))  # smallest along axis 0 ?
print(np.min(a, axis=1))  # smallest along axis 1, so first column
print(np.argmin(a))  # index of the smallest value, 0
print(np.argmax(a))  # index of the biggest value, 3
print(np.cumsum(a))  # cumulative sum in an array
print(np.mean(a))  # mean
print(np.var(a))  # variance (square mean of variance from mean)
print(np.std(a))  # standard dev (square root of variance)

10
[4 6]
[3 7]
1
4
[1 2]
[1 3]
0
3
[ 1  3  6 10]
2.5
1.25
1.118033988749895


In [ ]:
a = np.array([True, True, False])
print(np.all(a))  # sum of every boolean with boolean rules
print(np.any(a))  # any of the boolean

False
True


<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>5) Algebraic operations and linear algebra</i></span>

Algebraic manipulations of arrays are implemented in NumPy. They correspond to the standard operations of linear algebra on vectors, matrices, etc. More involved properties of linear algebra (eigenvalues and eigenvectors, inverse, etc.) need the <tt>linalg</tt> submodule.

For more details, consult <strong>§II.3.1</strong> of the lecture notes or the online documentation.

More involved functions (but also more efficient versions of the functions present in NumPy) are available in the sub-module <tt>scipy.linalg</tt> (but this will not be covered during the tutorials).

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code which illustrates the linear algebra manipulations of arrays. Add appropriate comments when required.</strong></span>
    </td>
  </tr>
</table>

In [ ]:
a = np.array([1, 2, 0])
b = np.array([3, 4, 5])
print(np.dot(a, b))  # dot product, term by term multiplication, gives a scalar (0D)
print(np.cross(a, b))  # cross product, returns a 1D (vector)
print(np.outer(a, b))  # a * b^T 

11
[10 -5 -2]
[[ 3  4  5]
 [ 6  8 10]
 [ 0  0  0]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.trace(a))  # trace of a (5 ?)
print(np.transpose(a))  # tranpose of a
print(a.T)  # tranpose of a
print(np.dot(a, b))  # product of the two matrices

5
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[19 22]
 [43 50]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])
print(np.dot(a, b))  # should return a vector
print(np.dot(b, a))  # cannot make the product !

[[17]
 [39]]


ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
print(np.dot(b, a))  # should return a vector
print(np.dot(a, b))  # can aswell

[23 34]
[17 39]


In [50]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b = np.array([2, 0, -1])
print(np.dot(a, b))  # COMMENT REQUIRED

[[-1  2]
 [ 5  8]]


In [51]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))  # COMMENT REQUIRED
print(np.linalg.det(a))  # COMMENT REQUIRED
print(np.linalg.eigvals(a))  # COMMENT REQUIRED
print(np.linalg.eig(a))  # COMMENT REQUIRED

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[-0.37228132  5.37228132]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([1, -1])
print(np.linalg.solve(a, b))  # solve AX = B ?
ainv = np.linalg.inv(a)
print(np.dot(ainv, b)) # same way of solving

[-3.  2.]
[-3.  2.]


<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>6) Mathematical functions</i></span>

The powerful feature of NumPy is that it provides already implemented, sometimes complicated, functions:
<ul style="list-style: none">
  <li><span style="font-size:11px"> ▶</span> trigonometric functions(<tt>sin</tt>, <tt>cos</tt>, <tt>arctan2</tt>, etc.) and constants ($\pi$);</li>
  <li><span style="font-size:11px"> ▶</span> hyperbolic functions (<tt>sinh</tt>, <tt>cosh</tt>, etc.);</li>
  <li><span style="font-size:11px"> ▶</span> exponential and logarithmic functions (<tt>exp</tt>, <tt>log</tt>, <tt>log10</tt>, etc.);</li>
  <li><span style="font-size:11px"> ▶</span> special function (<tt>i0</tt> - 0th modified Bessel function of the first kind -, <tt>sinc</tt>, etc.);</li>
  <li><span style="font-size:11px"> ▶</span> <tt>floor</tt>, <tt>ceil</tt>, <tt>sign</tt>;</li>
  <li><span style="font-size:11px"> ▶</span> radical functions (<tt>sqrt</tt>, <tt>abs</tt>, etc.);</li>
  <li><span style="font-size:11px"> ▶</span> functions for complex numbers (<tt>real</tt>, <tt>imag</tt>, <tt>abs</tt>, <tt>angle</tt>, <tt>conj</tt>, etc.).</li>
</ul>
NumPy applies all the elementary functions on <span style="color: #AB68B2;"><i>each individual item of the array</i></span> (element-wise operation).

More involved functions (but also more efficient versions of the functions present in NumPy) are available in the sub-module <tt>scipy.special</tt> (see TP5).

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code to understand how mathematical functions are applied to arrays. Add appropriate comments when required.</strong></span>
    </td>
  </tr>
</table>

In [53]:
print(np.cos(np.pi / 3.))
a = np.linspace(0., np.pi, 5)
print(a)
print(np.sin(a))
print(np.arctan2(1., 1.))  # COMMENT REQUIRED
print(np.arctan2(-1., 1.))  # COMMENT REQUIRED
print(np.arctan2(1., -1.))  # COMMENT REQUIRED
print(np.arctan2(-1., -1.))  # COMMENT REQUIRED

0.5000000000000001
[0.         0.78539816 1.57079633 2.35619449 3.14159265]
[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
0.7853981633974483
-0.7853981633974483
2.356194490192345
-2.356194490192345


In [ ]:
a = np.array([1.7, 2.5, 3.3, -4.4])
print(np.floor(a))  # lower round
print(np.ceil(a))  # upper round
print(np.sign(a))  # 1 or -1 depending on the sign

[ 1.  2.  3. -5.]
[ 2.  3.  4. -4.]
[ 1.  1.  1. -1.]


In [ ]:
a = np.array([-1.])
print(np.sqrt(a))  # doesnt work since the numpy array is a float, and sqrt would require a complex in this case

[0.70710678-0.70710678j]


In [57]:
a = np.array([-1.], dtype=complex)
print(np.sqrt(a))  # now works

[0.+1.j]


<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="sharing.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Conclude on the usage of <tt>arctan2</tt>.</strong></span>
    </td>
  </tr>
</table>

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="sharing.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> What can you also say about functions and types in NumPy?</strong></span>
    </td>
  </tr>
</table>

<span style="color: #E43F6F; font-size: 22px;"><strong>IV. Operations on arrays and vectorization</strong></span>


<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>1) Operations on arrays = Implicit loops</i></span>

The element-wise operations in NumPy, along with the reduction operations are very powerful because they allow you to implement <span style="color: #AB68B2;"><i>implicit loops</i></span>. Said differently, you can repeat operations on a list of elements without writing a loop explicitly. This method corresponds to the <span style="color: #AB68B2;"><i>vectorization of calculations</i></span>.

Vectorized calculations are usually <span style="color: #AB68B2;"><i>much faster/efficient</i></span> than their explicit-loop counterpart. <strong> This will be very helpful later during the class when we deal with the integration of ordinary and partial differential equations!</strong>

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code to appreciate the efficiency of vectorization.</strong></span>
    </td>
  </tr>
</table>

In [58]:
import time  # Module to measure times.
n = 100000
x = [i for i in range(n)]
v = [0.1 * (- 1) ** i for i in range(n)]
t0 = time.process_time()  # Value of the time at which the loop starts.
xp = []  # The objective is to sum x and v and to store the result in xp.
for i in range(n):  # Explicit loop with lists.
    xp += [x[i] + v[i]]
tf = time.process_time()  # Value of the time at which the loop ends.
print('Explicit loop CPU time =', tf - t0, 'seconds')
t0 = time.process_time()  # Value of the time at which the loop starts.
xarr = np.array(x)  # Arrays are built from lists.
varr = np.array(v)
xparr = xarr + varr  # Vectorized calculation with arrays.
tf = time.process_time()  # Value of the time at which the loop ends.
print('Vectorized loop CPU time =', tf - t0, 'seconds')

Explicit loop CPU time = 0.015625 seconds
Vectorized loop CPU time = 0.0 seconds


<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>2) Broadcasting to increase the range of operations on arrays</i></span>

As explained before, Python can perform element-wise operations on arrays if they have the same shape. However, operations on arrays of different shapes are possible if NumPy is able to transform these arrays so that they all have the same shape. This conversion is called <span style="color: #AB68B2;"><i>broadcasting</i></span>. For more details, consult <strong>§II.3.2</strong> of the lecture notes.

The operation between two arrays of different shapes is possible if their shapes are compatible. To check this compatibility, NumPy starts from the rightmost dimension and goes to the leftmost dimension. The shapes of the two arrays are compatible if all their dimensions are compatible, <i>i.e.,</i> if <span style="color: #AB68B2;"><i>they are equal</i></span> or <span style="color: #AB68B2;"><i>one of them is 1</i></span>.

The full list of operations which allow broadcasting is given here: https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs.

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code to understand the conditions which allow broadcasting. Add appropriate comments when required.</strong></span>
    </td>
  </tr>
</table>

In [59]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x)
print(v)
print(x.shape)
print(v.shape)
print(x + v)  # COMMENT REQUIRED

y = np.empty_like(x)
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)  # COMMENT REQUIRED

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
(4, 3)
(3,)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="sharing.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Conclude on the interest of broadcasting for vectorization.</strong></span>
    </td>
  </tr>
</table>

<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>3) Masking to use NumPy vectorization on a subset of array elements</i></span>

<span style="color: #AB68B2;"><i>Masking</i></span> extends the slicing (which corresponds to a contiguous selection of array elements) to the case of discontinuous selection of array elements. There are two possible ways for masking an array <tt>arr</tt>.
<ul style="list-style: none">
  <li><span style="font-size:11px"> ▶</span> One possibility is to provide an array of indices;</li>
  <li><span style="font-size:11px"> ▶</span> Another possibility is to provide an array which has the same shape as <tt>arr</tt> and which contains booleans <tt>True</tt> (if the element must be selected) or <tt>False</tt> (if not).</li>
</ul>
For more details, consult <strong>§II.3.3</strong> of the lecture notes. 

<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="programming.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Run the code to understand how masking works. Add appropriate comments when required.</strong></span>
    </td>
  </tr>
</table>

In [ ]:
a = np.array([-1., 2., -2., 0., 1.])
b = a > 0  # make a boolean array
print(a)
print(b)
print(a[b])  # use the array of boolean to select part of a
print(a[a > 0]) # same
a[a > 0] *= -1  # COMMENT REQUIRED
print(a)

[-1.  2. -2.  0.  1.]
[False  True False False  True]
[2. 1.]
[2. 1.]
[-1. -2. -2.  0. -1.]


In [ ]:
a = np.array([-1., 2., -2., 0., 1.])
ind = np.flatnonzero(a > 0)  # returns index of the non zero element
print(ind)
a[ind] *= -1  # COMMENT REQUIRED
print(a)

[1 4]
[-1. -2. -2.  0. -1.]


<table style="border: none;">
  <tr>
    <td style="vertical-align: middle;">
      <img src="sharing.png" width="40">
    </td>
    <td style="vertical-align: middle; padding-left: 10px;">
      <span style="color: #CF7EA0; font-size:16px;"><strong> Summarize the two different ways for masking an array.</strong></span>
    </td>
  </tr>
</table>

<span style="color: #E43F6F; font-size: 22px;"><strong>V. Exercises</strong></span>

<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>Exercise 1:</i></span>

In a two-dimensional vector space, consider an operator $A$ represented, in an orthonormal basis $\lbrace\vert 1\rangle, \vert 2\rangle\rbrace$, by the matrix
$$\sigma_y=\begin{pmatrix}
0&-i\\i&0
\end{pmatrix}.$$

1) Compute the eigenvalues $\lambda_1$, $\lambda_2$, and its eigenvectors $\vert u_1\rangle$ and $\vert u_2\rangle$. Check that the eigenvectors satisfy orthogonality relations (because $A$ is Hermitian).

2) Compute the unitary matrix $U$ such that $\sigma_y = U\Delta U^\dagger$ [with $\Delta=\mathrm{diag}(\lambda_1,\lambda_2)$] and check explicity this equality.

3) Compute the matrices $P_1$ and $P_2$ representing the projectors on the eigenvectors $\vert u_1\rangle$ and $\vert u_2\rangle$ respectively. Using these matrices, check that the eigenvectors satisfy a closure relation.

4) Calculate the products of matrices $P_1P_2$ and $P_2P_1$. Comment on your result.

In [3]:
sig = np.array([[0, -1j], [1j, 0]])
print(np.shape(sig))
eig_result = np.linalg.eig(sig)
eig_value, eig_vec = eig_result.eigenvalues, eig_result.eigenvectors
v1, v2 = eig_vec[:,0], eig_vec[:,1]  # see numpy documentation, eigenvectors are in column, not lines

print(v1, v2) 
print(f"Orthogonalité : {np.vdot(v1, v2)}") #vdot for complex conjugate (not only classical inner product .dot)


(2, 2)
[-0.        -0.70710678j  0.70710678+0.j        ] [0.70710678+0.j         0.        -0.70710678j]
Orthogonalité : -1.6653345369377348e-16j


In [4]:
delta = np.diag([eig_value[0], eig_value[1]])
U = eig_vec 

print(U@delta@U.conj().T)


[[-3.33066907e-16+0.j  0.00000000e+00-1.j]
 [ 0.00000000e+00+1.j  0.00000000e+00+0.j]]


In [9]:
P1 = np.outer(v1, v1.conj().T)
P2 = np.outer(v2, v2.conj().T)
print(P1 + P2)

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [11]:
print(np.dot(P1, P2))
print(np.dot(P2, P1))

[[-5.55111512e-17+0.00000000e+00j  0.00000000e+00-5.55111512e-17j]
 [ 0.00000000e+00-1.11022302e-16j  1.11022302e-16+0.00000000e+00j]]
[[-5.55111512e-17+0.00000000e+00j  0.00000000e+00+1.11022302e-16j]
 [ 0.00000000e+00+5.55111512e-17j  1.11022302e-16+0.00000000e+00j]]


<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>Exercise 2:</i></span>

A Hadamard matrix is a square matrix whose entries are either $1$ or $-1$ and whose rows are mutually orthogonal. 

For example:
$$ H_1=(1),$$
$$H_2=\begin{pmatrix}1&1\\1&-1\end{pmatrix},$$
$$H_4 =\begin{pmatrix}1&1&1&1\\1&-1&1&-1\\1&1&-1&-1\\1&-1&-1&1\end{pmatrix}.$$
There are two ways of constructing Hadamard matrices.

Sylvester's construction is based on the following property. If $H_n$ is a Hadamard matrix of order $n$, then the matrix $\begin{pmatrix}H_n &H_n\\H_n&-H_n\end{pmatrix}$ is a Hadamard matrix of order $2n$. Applying this construction iteratively from $H_1$ = $H_{2^0}$, we construct the sequence $H_{2^k}$ of Hadamard matrices.

Walsh's construction is based on the following procedure. If $F_1=\begin{pmatrix} 0&1\end{pmatrix}$ and if 
$F_k=\begin{pmatrix}0_{1\times 2^{k-1}}&1_{1\times 2^{k-1}}\\F_{k-1} &F_{k-1}\end{pmatrix}$, then you can obtain the Hadamard matrix $H_{2^k}$ for $k\geq 2$ from $A_{2^k}=F_k^TF_k\,\mathrm{mod}\,2$ by setting $$H_{2^k,ij}=\begin{cases}1\ &\text{if} &A_{2^k,ij}=0,\\-1&\text{if}&A_{2^k,ij}=1.\end{cases}$$

1) Define a function <tt>sylvester(k)</tt> which returns $H_{2^k}$ according to Sylvester's iterative construction.

2) Define a function <tt>walsh(k)</tt> which returns $H_{2^k}$ according to Walsh's iterative construction.

3) The Hadamard matrices verify $H_nH_n^T=nI_n$ where $I_n$ is the identity matrix of size $n$. Check this equality for $n=2^k$ and $k\leq 10$.

In [12]:
import numpy as np

def sylvester(k):

    h_list = [None]
    h_list[0] = np.array([1])

    for k in range(1, k+1):
        h_list.append(np.tile(h_list[k-1], (2,2)))
        h_list[k][
            np.shape(h_list[k])[0]//2:,
            np.shape(h_list[k])[0]//2:
            ] *= -1
    
    return h_list[k]

In [13]:
def walsh(k):

    f_list = [None]
    f1 = np.array([[0, 1]]) # DOUBLE BRACKET TO MAKE IT AN ACTUAL VECTOR WITH 2D INSTEAD OF A 1D ARRAY, TRANSPOSE AND STUFF WILL BREAK IF NOT
    f_list.append(f1)

    for k in range(2, k+1):
        f_list.append(np.zeros((k, 2**k), dtype=int))
        f_list[k][0:1,np.shape(f_list[k])[1]//2:] = 1
        f_list[k][1:,:] = np.hstack((f_list[k-1], f_list[k-1]))

    a = f_list[k].T@f_list[k] % 2
    h = np.ones(np.shape(a))

    for i in range(np.shape(a)[0]):
        for k in range(np.shape(a)[0]):
            if a[i, k] == 1:
                h[i, k] = -1

    return h

In [14]:
for k in range(1, 11):

    n = 2**k
    print(f"k = {k}, n = {n}, Sylvester's check : {np.allclose(sylvester(k)@sylvester(k).T - n*np.identity(n), 1e-16)}, Walsh's check : {np.allclose(walsh(k)@walsh(k).T - n*np.identity(n), 1e-16)}")


k = 1, n = 2, Sylvester's check : True, Walsh's check : True
k = 2, n = 4, Sylvester's check : True, Walsh's check : True
k = 3, n = 8, Sylvester's check : True, Walsh's check : True
k = 4, n = 16, Sylvester's check : True, Walsh's check : True
k = 5, n = 32, Sylvester's check : True, Walsh's check : True
k = 6, n = 64, Sylvester's check : True, Walsh's check : True
k = 7, n = 128, Sylvester's check : True, Walsh's check : True
k = 8, n = 256, Sylvester's check : True, Walsh's check : True
k = 9, n = 512, Sylvester's check : True, Walsh's check : True
k = 10, n = 1024, Sylvester's check : True, Walsh's check : True


<span style="color: #AB68B2; font-size: 18px; margin-left: 2em;"><i>Exercise 3:</i></span>

The (symmetric) matrix representing the inertia tensor of a collection of masses $m_i$ with positions $(x_i,\, y_i,\, z_i)$ relative to their centre of mass is:
$$I = \begin{pmatrix} I_{xx}&I_{xy} &I_{xz}\\I_{xy}&I_{yy}&I_{yz}\\I_{xz}&I_{yz}&I_{zz}\end{pmatrix},$$
where
$$\begin{aligned}
&I_{xx}=\sum_i m_i(y_i^2+z_i^2),\ I_{yy}=\sum_i m_i(x_i^2+z_i^2), \ I_{zz}=\sum_i m_i(x_i^2+y_i^2), \\
&I_{xy}=-\sum_i m_i x_iy_i,\ I_{xz}=-\sum_im_ix_iz_i,\ I_{yz}=-\sum_im_iy_iz_i.
\end{aligned}$$

There exists a transformation of the coordinate frame such that this matrix is diagonal: the axes of this transformed frame are called the principal axes and the diagonal inertia matrix elements, $I_a\leq I_b\leq I_c$ are the principal moments of inertia.

1) Write a function <tt>inertia_moments(mass,pos)</tt> which returns a one-dimensional array containing the ranked principal moments of inertia of a molecule, given the position and masses of its atoms relative to some arbitrary origin. Your function should first relocate the atom coordinates relative to its centre of mass and then determine the principal moments of inertia as the eigenvalues of the matrix $I$. The function must take two arrays as arguments: a one-dimensional array <tt>mass</tt> of size $N$ containing the masses of all atoms, and a three-dimensional array <tt>pos</tt> of shape $(N,\,3)$ containing the coordinates of all atoms. <strong> Do not use explicit loops! </strong>

2) Determine the principal moments of inertia of CH$_4$ given the following data:
#CH4

#Columns are: atom mass (atomic units), x ($\mathring{\rm A}$), y ($\mathring{\rm A}$), z ($\mathring{\rm A}$)

12.000 0.0000 0.0000 0.0000

1.0079 0.6276 0.6276 0.6276

1.0079 0.6276 -0.6276 -0.6276

1.0079 -0.6276 0.6276 -0.6276

1.0079 -0.6276 -0.6276 0.6276

In [ ]:
import numpy as np

def inertia_moments(mass, pos):

    # Just checking for proper shapes
    N = np.size(mass)
    if np.shape(pos) != (N, 3):
        raise Exception("Wrong shape for pos or mass array.")

    # Relocation of the atom coordinates relative to its center of mass
    x_com = np.sum(np.sum(pos[:, 0]*mass))/np.sum(mass)
    y_com = np.sum(np.sum(pos[:, 1]*mass))/np.sum(mass)
    z_com = np.sum(np.sum(pos[:, 2]*mass))/np.sum(mass)
    com_pos = np.array([x_com, y_com, z_com])

    pos_relocated = pos - np.tile(com_pos, (N, 1))

    # I computation 

    I = np.diag([np.sum(mass*(pos_relocated[:,1]**2 + pos_relocated[:,2]**2)), np.sum(mass*(pos_relocated[:,0]**2 + pos_relocated[:,2]**2)), np.sum(mass*(pos_relocated[:,0]**2 + pos_relocated[:,1]**2))])
    I[0,1] = I[1,0] = -np.sum(mass*pos_relocated[:,0]*pos_relocated[:,1])
    I[0,2] = I[2,0] = -np.sum(mass*pos_relocated[:,0]*pos_relocated[:,2])
    I[1,2] = I[2,1] = -np.sum(mass*pos_relocated[:,1]*pos_relocated[:,2])
    
    i1, i2, i3 = np.sort(np.linalg.eigvals(I))
    print(i1, i2, i3) #eigenvalues, principal moments of inertia

In [16]:
pos = np.array([[0, 0, 0,], [0.6276, 0.6276, 0.6276], [0.6276, -0.6276, -0.6276], [-0.6276, 0.6276, -0.6276], [-0.6276, -0.6276, 0.6276]])
mass = np.array([12, 1.0079, 1.0079, 1.0079, 1.0079])

inertia_moments(mass, pos)

3.175947407232001 3.175947407232001 3.175947407232001
