<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import RigidTransform as Tf
import numpy as np

Creating a transform from a single translation vector:


In [ ]:
t = np.array([2, 3, 4])
t + np.array([1, 0, 0])

array([3, 3, 4])

In [ ]:
tf = Tf.from_translation(t)
tf.apply([1, 0, 0])

array([3., 3., 4.])

In [ ]:
tf.single

True

The top 3x1 points in the rightmost column of the transformation matrix
is the translation vector:


In [ ]:
tf.as_matrix()

array([[1., 0., 0., 2.],
       [0., 1., 0., 3.],
       [0., 0., 1., 4.],
       [0., 0., 0., 1.]])

In [ ]:
np.allclose(tf.as_matrix()[:3, 3], t)

True

Creating multiple transforms from an N-dimensional array of translation
vectors:


In [ ]:
t = np.array([[2, 3, 4], [1, 0, 0]])
t + np.array([1, 0, 0])

array([[3, 3, 4],
       [2, 0, 0]])

In [ ]:
tf = Tf.from_translation(t)
tf.apply([1, 0, 0])

array([[3., 3., 4.],
       [2., 0., 0.]])

In [ ]:
np.allclose(tf.as_matrix()[:, :3, 3], t)

True

In [ ]:
tf.single

False

In [ ]:
len(tf)

2